LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;

ENTITY rom IS 
	PORT(DIR: IN INTEGER RANGE 0 TO 7;
	     SAL: OUT INTEGER RANGE 0 TO 15);
END ENTITY;

ARCHITECTURE BEAS OF rom IS 
TYPE MEMORY IS ARRAY(0 TO 7) OF INTEGER RANGE 0 TO 15;
CONSTANT ROM: MEMORY := (1,8,9,15,2,11,3,12); -- DATOS CALCULADOS
BEGIN
	SAL <= ROM(DIR);
END BEAS;